// Example bank data for supported countries/currencies
// In a real app, fetch this from an API or keep it up to date

export const banksByCurrency: Record<string, Array<{ code: string; name: string }>> = {
  NGN: [
    { code: '044', name: 'Access Bank' },
    { code: '011', name: 'First Bank' },
    { code: '058', name: 'GTBank' },
    { code: '214', name: 'First City Monument Bank' },
    { code: '221', name: 'Stanbic IBTC Bank' },
    { code: '232', name: 'Sterling Bank' },
    { code: '033', name: 'United Bank for Africa' },
    { code: '032', name: 'Union Bank' },
    { code: '023', name: 'CitiBank' },
    { code: '063', name: 'Access (Diamond) Bank' },
    { code: '050', name: 'Ecobank' },
    { code: '070', name: 'Fidelity Bank' },
    { code: '076', name: 'Polaris Bank' },
    { code: '082', name: 'Keystone Bank' },
    { code: '101', name: 'Providus Bank' },
    { code: '057', name: 'Zenith Bank' },
    { code: '030', name: 'Heritage Bank' },
    { code: '035', name: 'Wema Bank' },
    { code: '084', name: 'Enterprise Bank' },
    { code: '301', name: 'Jaiz Bank' },
  ],
  USD: [
    { code: 'BOA', name: 'Bank of America' },
    { code: 'CITI', name: 'Citibank US' },
    { code: 'WF', name: 'Wells Fargo' },
    { code: 'CHASE', name: 'JP Morgan Chase' },
    { code: 'USB', name: 'US Bank' },
    { code: 'CAP1', name: 'Capital One' },
    { code: 'PNC', name: 'PNC Bank' },
    { code: 'TD', name: 'TD Bank' },
    { code: 'TRUIST', name: 'Truist Bank' },
    { code: 'HSBC', name: 'HSBC US' },
  ],
  GBP: [
    { code: 'BARC', name: 'Barclays' },
    { code: 'HSBC', name: 'HSBC UK' },
    { code: 'LLOY', name: 'Lloyds Bank' },
    { code: 'NWBK', name: 'NatWest' },
    { code: 'RBS', name: 'Royal Bank of Scotland' },
    { code: 'TSB', name: 'TSB Bank' },
    { code: 'SANT', name: 'Santander UK' },
    { code: 'MONZ', name: 'Monzo' },
    { code: 'STAR', name: 'Starling Bank' },
  ],
  EUR: [
    { code: 'DEUT', name: 'Deutsche Bank' },
    { code: 'BNP', name: 'BNP Paribas' },
    { code: 'ING', name: 'ING' },
    { code: 'SANT', name: 'Santander' },
    { code: 'UBS', name: 'UBS' },
    { code: 'CREDIT', name: 'Credit Agricole' },
    { code: 'UNIC', name: 'UniCredit' },
    { code: 'BBVA', name: 'BBVA' },
    { code: 'COMMERZ', name: 'Commerzbank' },
    { code: 'SOCIETE', name: 'Societe Generale' },
  ],
  KES: [
    { code: 'KCB', name: 'Kenya Commercial Bank' },
    { code: 'EQUITY', name: 'Equity Bank' },
    { code: 'COOP', name: 'Co-operative Bank of Kenya' },
    { code: 'NCBA', name: 'NCBA Bank' },
    { code: 'STANBIC', name: 'Stanbic Bank Kenya' },
    { code: 'ABSA', name: 'Absa Bank Kenya' },
    { code: 'DTB', name: 'Diamond Trust Bank' },
    { code: 'FAMILY', name: 'Family Bank' },
    { code: 'SBM', name: 'SBM Bank Kenya' },
    { code: 'HF', name: 'Housing Finance Company' },
  ],
};
